### PR TITLE
Add a notification for when a user is speaking while muted

### PR DESCRIPTION
**Pull request by prprabhu-ms**
# What

image

# Why

Part of work to bubble up user facing diagnostics into the composite UI.

https://skype.visualstudio.com/SPOOL/_workitems/edit/2618495

### CODE REVIEW

**Comment by prprabhu-ms** [comment]
> We have some notification related components for errors and showing recording / transcription banners. Did you think about potentially consolidating the notifications?

https://github.com/Azure/communication-ui-library/pull/1008 has the common UFD notifications via the shared ErrorBar component.

**Review by alkwa-msft — APPROVED** [review]

**Comment by prprabhu-ms** [comment]
Kicked off stress test to make sure the UI tests aren't flaky after the mitigation: https://github.com/Azure/communication-ui-library/actions/runs/1409572326

**Comment by prprabhu-ms** [comment]
UI stress test again after updating snapshots: https://github.com/Azure/communication-ui-library/actions/runs/1409721951

**Comment by prprabhu-ms** [comment]
Keep stressing: https://github.com/Azure/communication-ui-library/actions/runs/1409984397

**Pull request merged**
