### PR TITLE
Fix flakey tests: regenerate y4m file without artifacts

### PR DESCRIPTION
**Pull request by JamesBurnside**
# What
* Update test video file (see why).
* In video ready also checked `!paused` to ensure video has loaded

# Why
Current file has some artifacts at the edge:
image

This appears to be causing following flakiness:
image

Bigger screenshot, see the black edge -- this is appearing _sometimes_ in tests:
image

This hasn't impacted us so far as it seems to fall outside playwrights threshold during our current tests, but adding landscape tests this does exceed the threshold

New File that doesn't appear to have any artifacts around the edge
image

# How Tested

Ran a bunch of times and haven't see the artifacts.
Stress test passed: https://github.com/Azure/communication-ui-library/runs/5841551173 ✅

### CODE REVIEW

**Comment by JamesBurnside** [comment]
Looks to have introduced its own flakiness:
image

Will reopen when fixed

**Comment by JamesBurnside** [comment]
Flaky start screen still happening

**Comment by JamesBurnside** [comment]
New y4m file

**Review by edwardlee-msft — APPROVED** [review]
One of the snapshots shows a scroll bar in the pip modal still. This will probably be resolved once updating the snapshots but thought I'll note this just in case.
[.../call-with-chat-gallery-screen-with-chat-pane-Mobile-Android-Portrait-linux.png](https://github.com/Azure/communication-ui-library/pull/1762/files#diff-80ca00db27324723b902acc818196b99b7b5553f9357ea18b3abff2e5d111f99)

**Review by dmceachernmsft — APPROVED** [review]

**Pull request merged**
