### PR TITLE
Rename OptionsButton -> DevicesButton

### PR DESCRIPTION
**Pull request by JamesBurnside**
# What
Rename OptionsButton -> DevicesButton

image

# Why

# How Tested
Run storybook and calling sample locally and was able to show and switch devices, labels shoed correctly.

### CODE REVIEW

**Review by alcail — APPROVED** [review]

**Comment by anjulgarg** [comment]
If I remember correctly, we were planning to use this button for encapsulating other things as well. Such as custom options, participants etc.
Any strong reasons for changing the name?

**Comment by JamesBurnside** [comment]
> If I remember correctly, we were planning to use this button for encapsulating other things as well. Such as custom options, participants etc. Any strong reasons for changing the name?

Reason mainly is - we're not using it for those purposes (and I don't see the plans to) and the word "options" is very vague. Hope is by renaming we can drive clarity in the buttons purpose. If we want a button in the future that does more - we can then release a new button that includes the extra functionality

**Comment by anjulgarg** [comment]
> > If I remember correctly, we were planning to use this button for encapsulating other things as well. Such as custom options, participants etc. Any strong reasons for changing the name?
> 
> Reason mainly is - we're not using it for those purposes (and I don't see the plans to) and the word "options" is very vague. Hope is by renaming we can drive clarity in the buttons purpose. If we want a button in the future that does more - we can then release a new button that includes the extra functionality

Alright. Don't have strong feelings on this. Approving.

**Review by anjulgarg — APPROVED** [review]

**Review by prprabhu-ms — APPROVED** [review]
very much LGTM.

**Comment by JamesBurnside** [comment]
Confirmed with AlexP the rename of options label to devices - so makes sense the name of the button follows suit

**Review by PorterNan — APPROVED** [review]

**Pull request merged**
