### PR TITLE
Remove tsc in app build and only do transipleOnly when rushx start

### PR DESCRIPTION
**Pull request by PorterNan**
# What

1. Remove tsc in app build
2. Only do transipleOnly when rushx start
3. Add conditional compilation to CallWithChat Sample app
# Why

# How Tested

# Process & policy checklist

- [ ] I have updated the project documentation to reflect my changes if necessary.
- [ ] I have read the [CONTRIBUTING](https://github.com/Azure/communication-ui-library/blob/main/CONTRIBUTING.md) documentation.

**Is this a breaking change?**

- [ ] This change causes current functionality to break.

### CODE REVIEW

**Review by JamesBurnside — APPROVED** [review]
Approved x1000

**Review by prprabhu-ms — APPROVED** [review]
What about StaticHTMLComposites, and ComponentExamples apps?

**Comment by prprabhu-ms** [comment]
Sending this PR on its way to unblock #1954

**Comment by PorterNan** [comment]
> > Sending this PR on its way to unblock #1954
> 
> Change looks to be causing out-of-memory exceptions /: image

That's weird, we don't add anything additional to the build, but only remove tsc from it

**Comment by JamesBurnside** [comment]
> That's weird, we don't add anything additional to the build, but only remove tsc from it

We are updating the build to have webpack perform type checking, must be tipping it over the edge, is there a way to increase the heap allocation?

**Comment by PorterNan** [comment]
> > That's weird, we don't add anything additional to the build, but only remove tsc from it
> 
> We are updating the build to have webpack perform type checking, must be tipping it over the edge, is there a way to increase the heap allocation for a node process? (or have we literally eaten all the RAM the build agent allows)

Looks like there is a logic problem, we are not enabling it, we are disabling type check in CI build but enable that in local development (Cause tsc was running in other pipeline already)

**Comment by JamesBurnside** [comment]
> Looks like there is a logic problem, we are not enabling it, we are disabling type check in CI build but enable that in local development (Cause tsc was running in other pipeline already)

Oh I thought it was the opposite way around, what pipeline type checks the sample code files?

**Comment by PorterNan** [comment]
> > Looks like there is a logic problem, we are not enabling it, we are disabling type check in CI build but enable that in local development (Cause tsc was running in other pipeline already)
> 
> I thought it was the opposite way around, what pipeline type checks the sample code files? The reason it was disabled for local development was it was taking so long so we decided to only typecheck at build&CI time

The original idea is - we need to disable typecheck in pipeline because it is not following conditional compilation

But I realized we might still need some typeguards for our ci build - so I add a conditional running tsc here - which will only run when it is beta

**Pull request merged**
