### PR TITLE
Added Czech localization

### PR DESCRIPTION
**Pull request by petrsvihlik**
# What
- Added resource strings for Czech language (cs-CZ)

# Why
- Enable more users

# How Tested

# Process & policy checklist

- [ ] I have updated the project documentation to reflect my changes if necessary.
- [ ] I have read the [CONTRIBUTING](https://github.com/Azure/communication-ui-library/blob/main/CONTRIBUTING.md) documentation.

**Is this a breaking change?**

- [ ] This change causes current functionality to break.

### CODE REVIEW

**Comment by JamesBurnside** [comment]
This is great thanks @petrsvihlik ! Were these translations fetched from the Touchdown service?

@mgamis-msft is there anything we would need to add to our touchdown pipeline tasks to ensure we continue to get czech translations when we complete this PR?

@alkwa-msft @ddematheu2 is there a reason we didn't include cs-cz lang from the start?

**Comment by petrsvihlik** [comment]
@JamesBurnside thanks for helping out with the pipeline issues!

> Were these translations fetched from the Touchdown service?

No, I translated it personally 😁 (What is the Touchdown service? 😇)

**Comment by mgamis-msft** [comment]
> This is great thanks @petrsvihlik ! Were these translations fetched from the Touchdown service?
> 
> @mgamis-msft is there anything we would need to add to our touchdown pipeline tasks to ensure we continue to get czech translations when we complete this PR?
> 
> @alkwa-msft @ddematheu2 is there a reason we didn't include cs-cz lang from the start?

Yes we would need to file a work item to change our Touchdown Build Configuration Setting like this: https://dev.azure.com/GlobalCollaborationService/Global%20Collaboration%20Service%20Project/_workitems/edit/242640

**Comment by petrsvihlik** [comment]
@mgamis-msft can I leave that to you? I have no knowledge of your internal systems :)

**Comment by JamesBurnside** [comment]
> No, I translated it personally 😁 (What is the Touchdown service? 😇)

Wow! Nice 😄 Touchdown is Microsoft's localization service - you give them en-us strings and they translate to many languages for you. Unfortunately we need touchdown to support the language otherwise any new strings/string changes we make won't be translated (unless we get you to translate everytime there's a new string haha).
If Touchdown supports cs-cz we can definitely keep these translations (as they are going to be much better than anything touchdown gives us) and future changes will be via touchdown.
But if we can't get touchdown to support cs-cz (for whatever reason) we unfortunately can't bring in these changes as we won't have support for future strings

**Comment by mgamis-msft** [comment]
> Thanks for the explanation! Please let me know if there is something left for me to do to get the PR merged :)

Hi @petrsvihlik, thank you for the translations! But as James mentioned we have to rely on Touchdown Build for translations for maintainability as we scale add more strings to our library. 
I will confirm with my PM to add cs-CZ to our Touchdown configuration and get the translated Czech strings from Touchdown Build. I will add you to PR with those Czech strings so you can have a look at the accuracy of the translation if you are interested :). If there are inaccuracies you can let me and I will contact Touchdown Build about it. I will close this PR. But once again thank you for your translations!

**Pull request closed without merging**
