### PR TITLE
Make adapter table narrower

### PR DESCRIPTION
**Pull request by PorterNan**
# What

Make adapter table narrower, basically the idea is to:

1. use `` to wrap individual variable name to ensure we can still wrap the text, without wrap the variable name
2. Merge columns to save width space

This is for bug:
https://skype.visualstudio.com/SPOOL/_workitems/edit/3930897/

# Why

# How Tested

# Process & policy checklist

- [ ] I have updated the project documentation to reflect my changes if necessary.
- [ ] I have read the [CONTRIBUTING](https://github.com/Azure/communication-ui-library/blob/main/CONTRIBUTING.md) documentation.

**Is this a breaking change?**

- [ ] This change causes current functionality to break.

### CODE REVIEW

**Comment by JoshuaLai** [comment]
Change looks good. But there was one other table I saw a follow up issue: 
image

**Review by JamesBurnside — CHANGES_REQUESTED** [review]
This should be fixable through CSS, if the issue is due to long `code` lines we should be able to apply something like `white-space: pre-line` (note sure the exact css but there should be some sort of line-break css we can apply)

--

Update: took a quick look and yeah removing the `white-space: nowrap` helps a lot. But like you have it we'll still need to drop to at most 3 columns or it's still too wide

**Comment by PorterNan** [comment]
> This should be fixable through CSS, if the issue is due to long `code` lines we should be able to apply something like `white-space: pre-line` (note sure the exact css but there should be some sort of line-break css we can apply)
> 
> --
> 
> Update: took a quick look and yeah removing the `white-space: nowrap` helps a lot. But like you have it we'll still need to drop to at most 3 columns or it's still too wide

Nice point about css, made the change and now it does not require extra attentions to the code snippet

**Comment by PorterNan** [comment]
> Change looks good. But there was one other table I saw a follow up issue: image

This is resolved through css as well

**Review by JamesBurnside — APPROVED** [review]

**Pull request merged**
