### PR TITLE
Converted video clips in VideoGallery storybook docs to GIFs

### PR DESCRIPTION
**Pull request by mgamis-msft**
# What

Converted video clips in VideoGallery storybook docs to GIFs

# Why

Requested by PM to avoid using videos in docs 

# How Tested

Please see generated chromatic

# Process & policy checklist

- [ ] I have updated the project documentation to reflect my changes if necessary.
- [ ] I have read the [CONTRIBUTING](https://github.com/Azure/communication-ui-library/blob/main/CONTRIBUTING.md) documentation.

**Is this a breaking change?**

- [ ] This change causes current functionality to break.

### CODE REVIEW

**Comment by JamesBurnside** [comment]
This gif for me has a very slow framerate which makes the feature look laggy (I assume it was the screen capture tool):
https://60c7ae6891f0e90039d7cd54-bwvjxxndlz.chromatic.com/images/video-gallery-pinning.gif

Any chance of re-recording this one?

**Comment by JamesBurnside** [comment]
These are also very zoomed in:
image

Does this have the wrong scaling mode constraint?

**Comment by JamesBurnside** [comment]
(loving the gifs!!)

**Review by dmceachernmsft — APPROVED** [review]

**Review by alkwa-msft — APPROVED** [review]

**Review by prabhjot-msft — APPROVED** [review]

**Comment by mgamis-msft** [comment]
WIll rerecord videos to make better quality GIFs in this bug https://skype.visualstudio.com/SPOOL/_workitems/edit/3252398

**Pull request merged**
