### PR TITLE
[Chat] Bump Chat SDK & Signaling to Latest Stable

### PR DESCRIPTION
**Pull request by jpeng-ms**
# What

bump Chat SDK and Signaling to latest stable release

# Why

OCE

# How Tested

# Process & policy checklist

- [ ] I have updated the project documentation to reflect my changes if necessary.
- [ ] I have read the [CONTRIBUTING](https://github.com/Azure/communication-ui-library/blob/main/CONTRIBUTING.md) documentation.

**Is this a breaking change?**

- [ ] This change causes current functionality to break.

### CODE REVIEW

**Review by JoshuaLai — APPROVED** [review]

**Comment by JoshuaLai** [comment]
Question do we usually put changelogs in for stable version bumps?

**Comment by palatter** [comment]
> Question do we usually put changelogs in for stable version bumps?

looks like we have in the past

image

**Review by palatter — APPROVED** [review]

**Review by emlynmac — APPROVED** [review]
Changes look good; looks like we have a question around whether we need to put a changelog in.

**Comment by jpeng-ms** [comment]
> > Question do we usually put changelogs in for stable version bumps?
> 
> looks like we have in the past
> 
> image

thanks updated

**Pull request merged**
