### PR TITLE
Moved locales folders up a level. Fix circular dependencies build error.

### PR DESCRIPTION
**Pull request by mgamis-msft**
# What

Moved locales in `packages/react-components` and `packages/react-composites locally` folders up a level.

# Why

To avoid this build error
image

# How Tested

Building `packages/react-components` and `packages/react-composites locally`

# Process & policy checklist

- [ ] I have updated the project documentation to reflect my changes if necessary.
- [ ] I have read the [CONTRIBUTING](https://github.com/Azure/communication-ui-library/blob/main/CONTRIBUTING.md) documentation.

**Is this a breaking change?**

- [ ] This change causes current functionality to break.

### CODE REVIEW

**Comment by prprabhu-ms** [comment]
I'm confused. Is the build broken on main? I didn't see any related CI failures.

**Comment by mgamis-msft** [comment]
> I'm confused. Is the build broken on main? I didn't see any related CI failures.

I'm not but the error in the description is blocking me from building the project locally and is resolved by this folder move.

**Comment by prprabhu-ms** [comment]
I saw this error before. Can you try rebuilding from scratch -- `rush rebuild`
I think this is caused by a folder left behind in the bundle from an earlier build (before these files were moved for the first time).

**Comment by mgamis-msft** [comment]
> I saw this error before. Can you try rebuilding from scratch -- `rush rebuild`
> I think this is caused by a folder left behind in the bundle from an earlier build (before these files were moved for the first time).

Yeah I just recloned the repo and everything is working now. I will try `rush rebuild` the next time the error happens again. Thanks. Closing this PR.

**Pull request closed without merging**
