### PR TITLE
Declare @azure/communication-react to be sideEffects free

### PR DESCRIPTION
**Pull request by prprabhu-ms**
Reduces the bundle size of an app with this:

```ts
import { EndCallButton, useCallingPropsFor } from "@azure/communication-react";

function App() {
  const endCallProps = useCallingPropsFor(EndCallButton);

  return (
    <div className="App">
      <EndCallButton {...endCallProps} />
    </div>
  );
}

export default App;
```

from 3.73 MB -> 2.79 MB (parsed), a reduction of 25%.

image
to
image

# Why
Better treeshaking. Less code, more happy kittens.

# How Tested
Built a brand new CRA app. Looked at source map and bundle analyzer reports.

# Process & policy checklist

- [x] I have updated the project documentation to reflect my changes if necessary.
- [x] I have read the [CONTRIBUTING](https://github.com/Azure/communication-ui-library/blob/main/CONTRIBUTING.md) documentation.

**Is this a breaking change?**

- [ ] This change causes current functionality to break.

### CODE REVIEW

**Comment by prprabhu-ms** [comment]
Pulling in `FluentThemeProvider` pulls in extra theming dependencies, pushing that number up to 3.1 MB (parsed). This is expected, and confirms that we indeed dropped the theming libraries earlier:

image

**Comment by JamesBurnside** [comment]
Nice find! Is sideEffects in the package.json a signal to webpack? I can't find documentation on it on the npm docs site. If so do other bundlers use the same flag?

**Comment by prprabhu-ms** [comment]
The difference is even bigger for chat. When using only `FluentThemeProvider` and `MessageThread`, the parsed size for the chunk goes down from 3.73 MB -> ~1MB

image
to
image

This is because @azure/communication-chat also sets `sideEffects: false` so we get tree shaking deeper into the tree.

**Comment by prprabhu-ms** [comment]
> Nice find! Is sideEffects in the package.json a signal to webpack? I can't find documentation on it on the npm docs site. If so do other bundlers use the same flag?

Yep: https://webpack.js.org/guides/tree-shaking/#mark-a-function-call-as-side-effect-free

**Comment by prprabhu-ms** [comment]
Will need to look at how rollup is handling this as well.

**Review by JamesBurnside — APPROVED** [review]

**Review by allenplusplus — APPROVED** [review]

**Pull request merged**
