### PR TITLE
Error bar text spacing fix

### PR DESCRIPTION
**Pull request by dmceachernmsft**
# What

Add `0.3rem` padding to the top of the fluent message bar
# Why

creates even spacing in the errorbar component between the text and the edges of the bar.
image

https://skype.visualstudio.com/SPOOL/_workitems/edit/2896682
# How Tested

Tested in storybook

### CODE REVIEW

**Review by edwardlee-msft — COMMENTED** [review]
Looks like the "X" is now not centered:
image

**Comment by dmceachernmsft** [comment]
> Looks like the "X" is now not centered: image

yeah this is something that wasn't reflected in the story book example. removed it for now and will do some more testing here in the actual app to see if this could be something with the test.

**Comment by edwardlee-msft** [comment]
Took a quick look, still looks like the Dismiss button X is still not centered. Will check back later today :)

**Review by JamesBurnside — APPROVED** [review]

**Review by edwardlee-msft — COMMENTED** [review]
Text in error bar seems to be a little off center for me.
Screen Shot 2022-06-28 at 9 16 56 AM
Screen Shot 2022-06-28 at 9 17 44 AM

**Review by edwardlee-msft — APPROVED** [review]

**Pull request merged**
