### PR TITLE
[RTE] Fix for rich text editor toolbar buttons hover state on Android devices

### PR DESCRIPTION
**Pull request by vhuseinova-msft**
# What

Previously, the rich text editor toolbar buttons (bold, italic...) were shown as selected even when the styles weren't applied. This PR is to fix this issue. 
Steps to reproduce:
-  open rich text editor send box page on Android device
- open a toolbar
- click "B" button
- type something
- click "B" button again
- check if the "B" button is not selected anymore 

# Why

# How Tested

# Process & policy checklist

- [x] I have updated the project documentation to reflect my changes if necessary.
- [x] I have read the [CONTRIBUTING](https://github.com/Azure/communication-ui-library/blob/main/CONTRIBUTING.md) documentation.

**Is this a breaking change?**

- [ ] This change causes current functionality to break.

### CODE REVIEW

**Review by emlynmac — APPROVED** [review]

**Comment by emlynmac** [comment]
@vhuseinova-msft do the snapshots need updating? Are they now reflecting what they should?

**Review by palatter — APPROVED** [review]

**Comment by palatter** [comment]
> @vhuseinova-msft do the snapshots need updating? Are they now reflecting what they should?

Ya looks like the original snapshot was not the intended behaviour and they should be updated.

**Comment by vhuseinova-msft** [comment]
> > @vhuseinova-msft do the snapshots need updating? Are they now reflecting what they should?
> 
> Ya looks like the original snapshot was not the intended behaviour and they should be updated.

@palatter you're right! Updating them right now

**Review by Leah-Xia-Microsoft — APPROVED** [review]
Tested on Android and can confirm the fix.

**Pull request merged**
