### PR TITLE
notification banner should not float on top of video gallery

### PR DESCRIPTION
**Pull request by alkwa-msft**
# What
We are going to have the compliance banner and any messages take up space and not hover over the video gallery

# Why
The messages would hover and partially cover the video tiles on the top of the gallery

# How Tested
Ran it locally.
Join from a Teams client first with your video on
Joined a teams interop call and started recording so I could see a recording banner.
*Should be getting a number of warnings that camera cannot be activated which also reduces the space of the screen below it instead of floating on top.

### CODE REVIEW

**Comment by alkwa-msft** [comment]
With no notifications
image

With a notification we see the video gallery have less space since the notification takes up space.
image

When the banner is dismissed the video gallery will take up the banner space as well.

**Review by JamesBurnside — APPROVED** [review]

**Comment by prprabhu-ms** [comment]
(1) Do we want the same for `ErrorBar` as well then?
(2) Non-floating banner was the initial implementation (a few months ago). We decided to float at that time because resizing the video tile was more disruptive. Do we have a reason to believe that resizing is better? Especially because resizing the videogallery could rearrange the tiles due to change in aspect ratio etc.

**Review by alcail — APPROVED** [review]

**Comment by alkwa-msft** [comment]
> (1) Do we want the same for `ErrorBar` as well then? (2) Non-floating banner was the initial implementation (a few months ago). We decided to float at that time because resizing the video tile was more disruptive. Do we have a reason to believe that resizing is better? Especially because resizing the videogallery could rearrange the tiles due to change in aspect ratio etc.

I think when we looked at the banner it looked like it was covering over some content.
It could potentially force a resize but considering the amount of height it takes up I don't think it will impact aspect ratio as much as we think?

**Review by mgamis-msft — APPROVED** [review]

**Review by prprabhu-ms — APPROVED** [review]

**Comment by alkwa-msft** [comment]
Confirmed that we want to keep it floating and we only want it to float over the gallery. It was doing this before so I am just going to close this PR.

**Pull request closed without merging**
